workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 60 # Maximum allowed build duration (in minutes)
    environment:
      flutter: stable
      vars:
        # Any environment variables you need to set
        FLUTTER_ROOT: $HOME/flutter
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build APK (Android)
        script: |
          flutter build apk --release
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/Runner.app
